name: Train MNIST Model

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training script
      run: |
        python train.py

    - name: Validate results
      run: |
        if grep -q "Final Accuracy: 99.4%" accuracy.txt; then
          echo "Validation passed: Target accuracy achieved."
        else
          echo "Validation failed: Target accuracy not achieved."
          exit 1 